### ISSUE TITLE
Grid view in Map Search breaks Advanced Search options

### ISSUE THREAD

**Issue by squigglysquid** [keriganmarketing/beachtimerealty#6]
To replicate the error:
Go into advanced search and click any of the 3 statuses -> click grid view -> go back to advanced search for this error:
![screen shot 2018-04-20 at 10 06 23 am](https://user-images.githubusercontent.com/35843681/39058957-e464baf0-4482-11e8-8d59-6ce902e8c97d.png)

Even if you go back into map search and click advanced settings, the error is there.

**Comment by programmer-man** [comment]
Resolved array to string conversion.
